apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: voter
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  selector:
    app: voter
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: NodePort
  selector:
    app: results
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001

