apiVersion: v1
kind: Service
metadata:
  name: results
spec:
  type: NodePort
  selector:
    app: result
    version: v1
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
        version: v1
    spec:
      containers:
       - name: result
         image: dockersamples/examplevotingapp_result:after
         ports:
          - containerPort: 80
